# Generated by Django 4.2.19 on 2025-03-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_chaivariety_image_store_chaireview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_varities',
            new_name='chai_varieties',
        ),
    ]
